name: 'Switch into Nix Shell'
description: 'Switch into a Nix shell and export environment variables to subsequent steps.'
author: 'Lukas Mertens'
inputs:
  nix_args:
    description: 'Additional arguments to pass to nix print-dev-env.'
    required: false
    default: ''
  install_nix:
    description: 'Whether to install Nix. Set to false if Nix is already installed.'
    required: false
    default: 'true'
  pure_env:
    description: 'Whether to use a pure nix environment.'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      if: ${{ inputs.install_nix == 'true' }}
      uses: cachix/install-nix-action@v27

    - name: Switch into Nix Shell
      shell: bash
      run: |
        set -e

        action_save_env=$(mktemp)
        action_before_env=$(mktemp)
        action_after_env=$(mktemp)
        action_diff_env=$(mktemp)

        cat - <<EOF >"$action_save_env"
          #!/usr/bin/env bash
          env | grep -E "^[a-zA-Z_][a-zA-Z0-9_]+=" | cut -d= -f1 | while read -r var; do
            value="\${!var}"
            # Replace newlines with \n for comparison
            escaped_value=\$(printf '%s' "\$value" | "$(which sed)" ':a;N;\$!ba;s/\\n/\\\\n/g')
            echo "\${var}=\${escaped_value}"
          done | "$(which sort)" > "\$1"
        EOF
        chmod +x $action_save_env

        # Save initial environment
        "$action_save_env" "$action_before_env"
        echo -e "\nOriginal environment variables"
        cat "$action_before_env"
        echo ""

        # Save environment after loading Nix shell
        nix develop ${{ inputs.nix_args }} ${{ inputs.pure_env == 'true' && '--ignore-environment' || '' }} --command "$action_save_env" "$action_after_env"
        echo -e "\nNix environment variables"
        cat "$action_after_env"
        echo ""

        # Unset changed variables from GITHUB_ENV
        diff "$action_before_env" "$action_after_env" | grep '^<' | sed -E 's/< ([^=]+).*/\1=""/' >> "$GITHUB_ENV" || true

        # Find differences
        diff "$action_before_env" "$action_after_env" | grep '^>' | sed 's/^> //' > "$action_diff_env" || true

        # Add changed variables to GITHUB_ENV
        echo -e "\nSetting variables"
        while IFS='=' read -r name value; do
          echo "$name=$value"

          # Unescape newlines
          unescaped_value=$(printf '%s' "$value" | sed 's/\\n/\n/g')

          echo "${name}<<EOF" >> "$GITHUB_ENV"
          echo "$unescaped_value" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
        done < "$action_diff_env"


branding:
  icon: 'terminal'
  color: 'blue'
